# Generated by Django 5.1.7 on 2025-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salary_max',
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='epoch',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
