# Generated by Django 5.1.7 on 2025-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_cv_is_parsed_cv_parsed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
