services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    command: celery -A skillsverse_backend worker -l info
    # restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    command: celery -A skillsverse_backend beat -l info
    # restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env
    command: celery -A skillsverse_backend flower --port=5555
    # restart: unless-stopped

volumes:
  redis_data: